ubnt-intrepid/polyfuse

fuse-async-channel/Cargo.toml
fuse-async-channel/src/tokio.rs
src/lib.rs
src/reply.rs
src/session.rs

In modified `Session`, the futures generated by the provided `Operations` are not run immediately, but added to the background task pool and executes concurrently with the other request tasks.
fix #13.
Unresolved problems:
* `ReplyRaw` without cloning the I/O object
* Interrupt mechanism
* Appropriate scheduling to execute the receiving tasks and background request tasks

switch to multiplex session driver

---

examples/hello.rs
src/lib.rs
src/server.rs
src/session.rs
src/session/buf.rs
src/session/reply.rs
src/session/request.rs

Limitations:
* There are additional allocation cost when a `FUSE_NOTIFY_REPLY` request is received and pass its payload through the sender.

add experimental support for notification

---

examples/examples/heartbeat.rs
examples/examples/heartbeat_entry.rs
examples/examples/hello.rs
examples/src/lib.rs
examples/src/memfs/mod.rs
polyfuse-tokio/Cargo.toml
polyfuse-tokio/src/channel.rs
polyfuse-tokio/src/server.rs
polyfuse/src/fs.rs
polyfuse/src/init.rs
polyfuse/src/io.rs
polyfuse/src/lib.rs
polyfuse/src/notify.rs
polyfuse/src/op.rs
polyfuse/src/reply.rs
polyfuse/src/request.rs
polyfuse/src/session.rs
polyfuse/src/util.rs

It replaces the current `futures-io` based I/O abstraction, in order to better represent the FUSE-specific I/O operations, including `splice(2)`.
The older `request::Buffer` is removed and the `request` module becomes private.
Closes #50.

add FUSE-specific I/O abstraction

---

examples/examples/hello.rs
polyfuse/src/fs.rs
polyfuse/src/session.rs

The current implementation around handling the INTERRUPT request is incomplete and we need to reconsider a more efficient, runtime-aware way.

 remove (temporarily) the interrupt support

---

polyfuse/src/op.rs

Note: methods in some operations are deprecated.

add doc comments to operation types

---

examples/examples/passthrough.rs
examples/src/lib.rs
polyfuse/src/context.rs
polyfuse/src/dirent.rs
polyfuse/src/init.rs
polyfuse/src/io.rs
polyfuse/src/op.rs
polyfuse/src/reply.rs
polyfuse/src/session.rs

The new trait `ScatteredBytes` is introduced in the `io` module for abstracting the discontinuous chunks of byte data.

introduce abstraction for representing scattered bytes

---

examples/Cargo.toml
examples/examples/memfs.rs
examples/examples/passthrough/main.rs
polyfuse/src/common.rs
polyfuse/src/context.rs
polyfuse/src/dirent.rs
polyfuse/src/init.rs
polyfuse/src/io.rs
polyfuse/src/kernel.rs
polyfuse/src/op.rs
polyfuse/src/reply.rs
polyfuse/src/session.rs
polyfuse/src/util.rs

It switches the `Debug` implementations in some public types to the manual, instead of using `#[derive(Debug)]`.
This is also intended to hide the implementation details around the message data from the kernel and to prevent unexpected leakage of the unprocessed data to the user side, and hence it has more than just to improve the readability of debugging log messages.
At the same time, the unused `Debug` derivations and the tracing output inside the library are removed.

improve the fmt::Debug implementations in public types

---

polyfuse/src/common.rs
polyfuse/src/lib.rs
polyfuse/src/op.rs

Note: according to　the implementation of the FUSE kernel driver, `lock_owner` contains the value of encrypted `lk_owner_t` using XTEA.

add LockOwner to protect the raw identifier from the kernel

---

examples/examples/memfs.rs

This is necessary for seeking in modes like 'r+' to work.

Fix bug in memfs example that truncates after every write.

---

README.md

Using a relative link here doesn't work, e.g. when viewing it rendered at https://github.com/ubnt-intrepid/polyfuse/tree/master/polyfuse. See also https://gitlab.com/crates.rs/crates.rs/-/issues/57.

Make 'Examples' link absolute

---

.gitmodules
Cargo.toml
polyfuse-kernel/Cargo.toml
polyfuse-kernel/src/lib.rs
polyfuse-kernel/systest/Cargo.toml
polyfuse-kernel/systest/build.rs
polyfuse-kernel/systest/tests/test_kernel.rs
polyfuse/Cargo.toml
polyfuse/src/lib.rs
polyfuse/systest/src/lib.rs

The extract package is currently used by the core package, but it
will be used directly by the async runtime support packages in the
future.
bors: r+

extract polyfuse-kernel

---

crates/polyfuse/src/conn.rs

If the filesystem does not implement signal handling, the mountpoint
will not appropriately released since the destructor of Connection
is not appropriately called.
To prevent such situation, enabling `auto_unmount` option by default to
ensure that corresponding mountpoint is released at the end of process.
bors: r+

enable -o auto_unmount by default

---

crates_deprecated/polyfuse-tokio/Cargo.toml
crates_deprecated/polyfuse-tokio/README.md
crates_deprecated/polyfuse-tokio/src/lib.rs

This release is just to announce the end of maintenance for crate users.
bors: r+

bump polyfuse-tokio to 0.2.3

---

crates/polyfuse/src/reply.rs

the current size of the reply buffer is checked if the to-be-added entry
after aligning fits in the buffer. And if it does the entry get added
and the buffer is resized to (bufferlen + aligned-size-of-entry).
Here the entry-size is included twice, once in bufferlen and once in
aligned-size-of-entry. As as result the initial capacity of the buffer
if overflowing get increased as a result sending back an invalid sized
buffer, which get rejected giving out an "Input/Output Error" from the
kernel to the user.
The path fixes this behaviour by getting the size of before adding the
new entry and extending it by align-size-of-entry

fix overflowing the reply buffer for readdir

---

crates/polyfuse/src/conn.rs
crates/polyfuse/src/lib.rs
crates/polyfuse/src/session.rs
examples/basic/src/main.rs
examples/heartbeat-entry/src/main.rs
examples/heartbeat/src/main.rs
examples/hello/src/main.rs
examples/memfs/src/main.rs
examples/passthrough/src/main.rs
examples/path-through/src/main.rs
examples/poll/src/main.rs
examples/with-tokio/src/main.rs

FUSE セッションの初期化プロセス
1. `/def/fuse` オープンし fd を取得
2. `mount(2)` でマウントポイントと上の fd を紐付ける
3. `opcode=FUSE_INIT` を処理し ABI version 等の設定をネゴシエーション
のうち、1. と 2. は `Connection::open` 部分に集約しているので `Session::mount` から分離可能。
また、3. については `AsyncRead/AsyncWrite` による抽象化によって容易に非同期化が出来る:
```rust
impl<T> Session<T>
where
T: AsyncRead + AsyncWrite,
{
async fn init(conn: T, ...) -> io::Result<()> {
...
}
}
```
このPRをマージした後、`Connection` のインスタンスを `Session` が保持するのを止め通信毎に `&conn` で渡すようにする。

Expose the initialization process of `Connection` from `Session`

---

crates/polyfuse/src/session.rs
examples/heartbeat-entry/src/main.rs
examples/heartbeat/src/main.rs
examples/memfs/src/main.rs

本来であればここで一気に `AsyncRead` / `AsyncWrite` を使用したいが、差分が大きくなりすぎるので `io::Read` / `io::Write` を使用する。
https://github.com/ubnt-intrepid/polyfuse/pull/173#discussion_r2247708055 での指摘の通り、この抽象化によって FUSE デバイスの実装に柔軟性をもたせることが可能になる。

use I/O abstraction instead of passing `&mut Connection` directly

---

Cargo.lock
crates/polyfuse/Cargo.toml
crates/polyfuse/src/session.rs

今までは `FUSE_INIT` が来る前に受信したリクエストに雑に返答した後廃棄していたが、バッファに保持しておき `Session::next_request` 時に取り出すようにした。
`FUSE_INIT` まわりの処理に関する代替案:
* 他の opcode と同格に扱い、セッションの初期化を遅延する
- `libfuse` や `fuser` などはこの方針を用いている
- `Session` を共有している場合、設定を書き替える際のロックまわりを考えるのが面倒

store incoming requests to the queue received during `Session` initialization

---

Cargo.lock
crates/polyfuse/Cargo.toml
crates/polyfuse/src/session.rs

カーネル側の実装によると、
* [`fuse_conn.initialized`](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/fs/fuse/fuse_i.h?h=v6.15.9#n693) フラグがセットされるまで任意のリクエストのenqueueはブロックされる
* このフラグがセットされるのは `FUSE_INIT` のリプライを受け取り、初期化処理が完了した後のみである (`process_init_reply` 関数の最後）
とのことなので、カーネル側の実装に不備がある（パッチが当たってたりなど）場合を除けばセッション初期化が完了する前にリクエストが飛んでくることはないので無視できる。
そこで、#180 で導入した `pending_requests` を再び削除し、ログにエラーを表示させるようにした。

remove storing incoming requests before FUSE_INIT

---

Cargo.lock
crates/polyfuse/Cargo.toml
crates/polyfuse/src/lib.rs
crates/polyfuse/src/session.rs
examples/passthrough/src/main.rs

- ~~テストを整理し、カバレッジを改善する~~ → 別PRで対処

reimplement the session initialization: part 2

---

examples/heartbeat.rs
examples/memfs.rs
examples/passthrough/main.rs
examples/path_through.rs
src/lib.rs
src/op.rs
src/session.rs

この後 `readv(2)` へのフォールバックや #148 相当のバッファ再利用関連の処理を実装するにあたり、ごちゃごちゃしている部分を簡単にしておく
* フォールバックを見据えて `splice(2)` で使用したパイプを `Option` で保持していたが、現状必要ないのでフラットにした
* `Data` を削除し、`Request` に直接 `io::Read` を実装した
* `Operation` に `Data` を渡すのを止める

`Request` まわりの実装を簡略化

---

examples/basic.rs
examples/hello.rs
examples/memfs.rs
examples/path_through.rs
src/nix.rs
src/session.rs

このPRは #148 の引き継ぎであり、これまでリクエスト毎に生成していた `Request` のインスタンスを再利用可能にする。
元々は `readv(2)` における余計なアロケーションを防ぐためのものであったが、`splice(2)` 下でも依然として必要な処置であるため今のうちに実装しておく。
closes #148 .

Make the request buffer reusable

---

examples/basic.rs
src/fs.rs
src/lib.rs
src/nix.rs
src/request.rs
src/session.rs

* 該当コードを `src/request.rs` に移動
* `fs::Request` との混同を避けつつ、本来の役割と合わせるため名称を `RequestBuffer` に変更
TODOs:
- ~~`FUSE_SPLICE` の有無によるフォールバック処理の実装~~ →別PRで対応

Tidy up implementation around request buffer

---

examples/basic.rs
examples/heartbeat.rs
examples/heartbeat_entry.rs
examples/hello.rs
examples/memfs.rs
examples/passthrough/main.rs
examples/path_through.rs
examples/poll.rs
src/fs.rs
src/op.rs

* 各 op が `fuse_in_header` や `fuse_XXX_in` への参照を保持するのではなく、解析後の結果を持つようにする

Re-design the decoded filesystem operations

---

Cargo.toml
examples/basic.rs
src/conn.rs
src/fs.rs
src/mount.rs
src/mount/privileged.rs
src/mount/unpriv.rs
src/mount/unprivileged.rs

特権マウントを実装しつつ、全体的に整理する
* `fusermount` への fallback は実装しない
* `/etc/mtab` の書き込みは行わない
- libfuse で `IGNORE_MTAB` が常に有効化されているような状態

add support for privileged mount

---

.gitmodules
Cargo.toml
crates/polyfuse-kernel-systest/README.md
crates/polyfuse-kernel-systest/build.rs
crates/polyfuse-kernel-systest/include/fuse_kernel.h
crates/polyfuse-kernel-systest/include/fuse_kernel_compat.h
crates/polyfuse-kernel-systest/tests/test_kernel.rs
crates/polyfuse-kernel/src/lib.rs
src/bytes.rs
src/conn.rs
src/fs.rs
src/op.rs
src/reply.rs
src/session.rs

* `libfuse` を経由すると ABI version の融通がきかないので、kernel.org から直接入手する
* 可能な限り新しいバージョンの ABI に追従させる
* カーネル側が古い ABI を使用している場合に対応できるよう、古いバージョンの構造体についても定義しておく

polyfuse-kernel: bump ABI version to the latest
