- .github/workflows/ci-workflow.yml
* add restriction to memory usage
* add timeout to each `cargo-doc`
* upload artifact after building
> CI: fix DeployMasterDoc job

- src/session.rs
- src/session/fs.rs
- src/session/reply.rs
- src/session/request.rs
> add poll operation

- examples/examples/heartbeat.rs
- examples/examples/heartbeat_entry.rs
- examples/examples/hello.rs
- examples/src/lib.rs
- examples/src/memfs/mod.rs
- polyfuse-tokio/Cargo.toml
- polyfuse-tokio/src/lib.rs
- polyfuse/Cargo.toml
- polyfuse/src/fs.rs
- polyfuse/src/lib.rs
- polyfuse/src/op.rs
- polyfuse/src/reply.rs
- polyfuse/src/session.rs
> improve the ergonomics of Filesystem

- .cargo-husky/hooks/pre-commit
- .github/workflows/doc.yml
- .github/workflows/test.yml
- xtask/Cargo.toml
- xtask/src/hook.rs
- xtask/src/main.rs
> xtask: brush up

- .github/workflows/test.yml
> ci: remove unnecessary predicates from condition

- .github/workflows/test.yml
- polyfuse/src/init.rs
- polyfuse/src/reply.rs
> Silence lint warnings on CI

- polyfuse-tokio/src/channel.rs
Checks the exit status of `fusermount` command before receiving the
file descriptor, and exits immediately if failed.
Fixes #84.
bors: r+
> Check the fusermount exit status after spawning

- polyfuse-tokio/CHANGELOG.md
- polyfuse-tokio/Cargo.toml
- polyfuse-tokio/src/lib.rs
> bump polyfuse-tokio to 0.2.1

- .github/workflows/test.yml
- Cargo.toml
- polyfuse-tokio/Cargo.toml
- polyfuse-tokio/README.md
- polyfuse-tokio/src/lib.rs
- polyfuse/Cargo.toml
- polyfuse/src/lib.rs
* bump `polyfuse` to `0.4.0-dev`
* migrate `polyfuse-tokio` to maintenance mode
bors: r+
> start the iteration to 0.4.x

- polyfuse/src/context.rs
- polyfuse/src/fs.rs
- polyfuse/src/io.rs
- polyfuse/src/lib.rs
- polyfuse/src/session.rs
> remove io::{Reader,Writer}

- README.md
> update information in README.md

- crates/polyfuse-daemon/src/op.rs
- crates/polyfuse-daemon/src/reply.rs
- crates/polyfuse-daemon/src/request.rs
- crates/polyfuse/src/op.rs
- examples/basic/src/main.rs
* remove method to access request info (such as `unique`)
* remove `Reply` associations
bors: r+
> simplify operation traits

- crates/polyfuse/src/reply.rs
- crates/polyfuse/src/request.rs
- examples/basic/src/main.rs
- examples/hello/src/main.rs
> switch from callback based operation handling

- .github/workflows/test.yml
- xtask/Cargo.toml
- xtask/src/doc.rs
- xtask/src/env.rs
- xtask/src/hook.rs
- xtask/src/lint.rs
- xtask/src/main.rs
- xtask/src/process.rs
> upgrade dev tools

- crates/polyfuse/Cargo.toml
- crates/polyfuse/src/session.rs
> re-enable unit test for session initialization

- crates/polyfuse-kernel/src/lib.rs
- crates/polyfuse/src/lib.rs
- crates/polyfuse/src/op.rs
- crates/polyfuse/src/session.rs
> Enable missing filesystem operation and miscellaneous utilities

- crates/polyfuse-async-std/Cargo.toml
- crates/polyfuse-async-std/src/lib.rs
- crates/polyfuse-mount/Cargo.toml
- crates/polyfuse/src/conn.rs
- crates/polyfuse/src/lib.rs
- crates/polyfuse/src/mount.rs
- crates/polyfuse/src/syscall.rs
- xtask/src/doc.rs
> hydrate polyfuse-mount into polyfuse

- crates/polyfuse/src/session.rs
> use vectored read in session initialization

- crates/polyfuse/src/op.rs
- crates/polyfuse/src/reply.rs
- crates/polyfuse/src/session.rs
Note that these debug outputs are out of semver compatibility.
bors: r+
> impl fmt::Debug for op/reply types

- crates/polyfuse/src/conn.rs
> fix conn::mount()

- crates/polyfuse/src/decoder.rs
> add unit tests for Decoder

- crates/polyfuse-kernel/src/lib.rs
> bump ABI version to 7.31 (in libfuse 3.10.1)

- crates/polyfuse/Cargo.toml
- crates/polyfuse/src/bytes.rs
- crates/polyfuse/src/notify.rs
- crates/polyfuse/src/reply.rs
- examples/memfs/Cargo.toml
- examples/memfs/src/main.rs
- examples/passthrough/Cargo.toml
- examples/passthrough/src/main.rs
> upgrade abstraction of scattered bytes

- crates/polyfuse/src/notify.rs
> correct length value in notification payloads

- crates/polyfuse/Cargo.toml
- crates/polyfuse/src/conn.rs
- crates/polyfuse/src/lib.rs
- crates/polyfuse/src/session.rs
- examples/basic/src/main.rs
- examples/heartbeat-entry/src/main.rs
- examples/heartbeat/src/main.rs
- examples/hello/src/main.rs
- examples/memfs/src/main.rs
- examples/passthrough/src/main.rs
- examples/path-through/src/main.rs
- examples/poll/src/main.rs
- examples/with-async-std/src/main.rs
- examples/with-tokio/src/main.rs
This type is used as a set of setting parameters for both
mounting and handling FUSE_INIT requests.
bors: r+
> introduce KernelConfig

- README.md
> correct Discord invitation URL in badge

- xtask/Cargo.toml
- xtask/src/coverage.rs
- xtask/src/env.rs
- xtask/src/main.rs
> improve coverage xtask

- examples/memfs/Cargo.toml
- examples/memfs/src/main.rs
> update example: memfs

- crates/polyfuse/CHANGELOG.md
- crates/polyfuse/Cargo.toml
> bump polyfuse to 0.4.1

- Cargo.lock
- crates/polyfuse/Cargo.toml
- crates/polyfuse/src/session.rs
こういう小手先の変更はバグの温床になりがちなので避けましょう…
> revert the code about the memory alignment of request data

- src/types.rs
> adjust the inner representation of DeviceID to the actual spec

- crates/polyfuse/src/conn.rs
- On musl, libc::msghdr has private padding fields; construct via zero-init and set public fields.
- On musl, msg_controllen is socklen_t (u32); on glibc it's size_t (usize), hence TryInto
Sorry about the misunderstanding
Jan
> Musl build:
